import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <nav className="border-b p-4 flex gap-4">
          <a href="/test-cases" className="font-medium hover:underline">
            Test Cases
          </a>
          <a href="/suites" className="font-medium hover:underline">
            Suites
          </a>
          <a href="/runs" className="font-medium hover:underline">
            Runs
          </a>
        </nav>
        {children}
      </body>
    </html>
  );
}
